# Site settings
title: R.Kueny
header-img: img/home-bg.jpg
email: raphael@rkueny.fr
description: "Description meta"
baseurl: ""
url: "http://rkueny.github.io/"
twitter_username: rkueny
github_username:  rkueny
facebook_username:  rkueny.freelance

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
