# site settings
title: R.Kueny
subtitle: Consultant & Développeur Web
email: raphael@kueny.me
description: Expert Symfony - Fervent développeur avec ReactJs et React Native.
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 12 impasse des violettes
city: Ayguesvives
state: ""
zip_code: 31450
country: France
phone: ""

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/rkueny
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/rkueny
pinterest_url:
slack_url:
twitter_url: https://twitter.com/rkueny

# build settings
markdown: kramdown

sass:
  style: compressed
