# Site settings
title: R.Kueny
header-img: img/home-bg.png
email: raphael@kueny.fr
description: "R.Kueny CTO @ Monkees/Publicis - Toulouse."
baseurl: ""
url: "http://rkueny.fr"
twitter_username: rkueny
github_username:  rkueny
facebook_username:  rkueny.freelance

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems : [jekyll-paginate]
