title: CTO et Consultant Web
description: > # this means to ignore newlines until "baseurl:"
  R.Kueny CTO & Consultant Web
  Dans le monde du web depuis plus de 10 ans, mon expertise se porte principalement sur Symfony et l'écosystème PHP.
  Je suis aussi un fervent utilisateur de React et React Native.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kueny.me" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Raphaël Kueny # add your name
author-img: rkueny.jpg # add your photo
social-twitter: rkueny # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: rkueny # add your Github handle
social-linkedin: rkueny # add your Linkedin handle
social-email: raphael@kueny.me # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
