# Site settings
title: R.Kueny | Developer web
header-img: img/home-bg.png
email: raphael@kueny.fr
description: "R.Kueny développeur web à Toulouse. J'utilise PHP, Symfony2, les API (réseaux sociaux notamment). Je fais aussi du développement mobile à l'aide de Titanium Appcelerator"
baseurl: ""
url: "http://rkueny.fr"
twitter_username: rkueny
github_username:  rkueny
facebook_username:  rkueny.freelance

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
